version: "3.9"
services:
  stack:
    build: ./
    ports:
      - "3000:80"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: OZr*ca^(H=r"*^;#SktbGSwX79K|ep)[g{ao4jHh
      POSTGRES_DB: PV2
    networks:
      - default
  postgres:
    #image: postgres:14.1
    build: ./backend/database/
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: OZr*ca^(H=r"*^;#SktbGSwX79K|ep)[g{ao4jHh
      POSTGRES_DB: PV2
    networks:
      - default